### ISSUE TITLE
IntelliJ

### ISSUE THREAD

**Issue by omidb** [ruippeixotog/scala-scraper#1]
Hi, thanks for the library,

I don't know why IntelliJ is not happy with  `>> elemnts("something") ` syntax and it makes is red, it compiles it though.

**Comment by ruippeixotog** [comment]
Hi, thanks for using the library! :)

Yes, I also use IntelliJ and it's very annoying that I have to disable type-aware highlighting when I use scala-scraper. I believe the error boils down to implicit conversions between two functions, which seems to confuse IntelliJ. Here is a minimal example:

```scala
object Main extends App {
  // some implicit conversion between functions, doesn't matter its body or type
  implicit def convert(f: Int => Int): (String => String) = { s: String => "a" * f(s.length) }

  val f: (Int => Int) = { n: Int => n * 2 }
  f("hello") // highlighting error
}
```

It seems a rather strange use case for an implicit conversion by looking at this example alone, but in scala-scraper it allows content extractors like `elements` to be either directly used as extractors or used as an argument to the full `extractor` constructor. It is an IntelliJ bug and it should be reported, but I didn't find the time to submit the issue to them yet :(

**Comment by omidb** [comment]
maybe you can submit your comment here exactly there, they are very active.

**Comment by ruippeixotog** [comment]
Will do it, probably this weekend.

**Comment by ruippeixotog** [comment]
I have just submitted the issue: https://youtrack.jetbrains.com/issue/SCL-8157

**Comment by omidb** [comment]
cool

**Comment by ruippeixotog** [comment]
Hi! Just to let you know that the issue was fixed today on JetBrains' part. It should be available in the version 1.7.70 of the Scala plugin.

Once it is released and I'm able to check it, I'll close this.

**Comment by omidb** [comment]
nice!

**Comment by hkirk** [comment]
Seems that this is broken again - I'm using scala plugin 1.9.2 and getting errors again. Can anyone confirme this?

Thanks for a nice lib

**Comment by pboehm** [comment]
I can confirm this using IntelliJ IDEA 15 EAP with Scala Plugin 1.9.2.2
<img width="399" alt="intellij_highlighting_problem" src="https://cloud.githubusercontent.com/assets/665684/10524730/5f270c1e-7381-11e5-8c0d-303637842aae.png">

**Comment by ruippeixotog** [comment]
I'm using 1.9.2.2 too and I can also confirm that syntax highlighting yields false syntax highlighting errors.

I'll find some time this weekend to reduce this to a minimal example and create a new issue in the IntelliJ issue tracker.

**Comment by ruippeixotog** [comment]
I've reduced the problem to a minimum example and submitted [an issue](https://youtrack.jetbrains.com/issue/SCL-9306) to the Scala plugin team. As I think they prioritize the issues by the number of voters, it would help very much if you voted up the issue there! (it requires creating an account on their issue tracker...)

**Comment by ruippeixotog** [comment]
The Scala plugin issue I submitted was fixed a few days ago. I tested the fixes and most of the syntax highlighting errors were fixed. I expect the fixes should appear in the next version of the plugin for IntelliJ 16 (I'm not so sure about IntelliJ 15). I'm closing this issue, hopefully permanently :)
