### ISSUE TITLE
Scala 3 release

### ISSUE THREAD

**Issue by francisdb** [ruippeixotog/scala-scraper#168]
The migration guide is here 
https://docs.scala-lang.org/scala3/guides/migration/compatibility-intro.html

**Comment by ruippeixotog** [comment]
Looks like Scalaz only has milestone releases for Scala 3 (https://mvnrepository.com/artifact/org.scalaz/scalaz-core). I am not very fond of introducing milestone dependencies, so let's wait a bit more for things to get more stable on the scalaz side.

**Comment by Gonzih** [comment]
You can have your own milestone release that uses other milestone releases :) Would help other people to prepare for the migration on their codebase

**Comment by francisdb** [comment]
Looks like there still is no final scala 3 version of scalaz (7.4.0-M8)

**Comment by Arthurm1** [comment]
Is this OK to use [7.3.6](https://search.maven.org/artifact/org.scalaz/scalaz-core_3/7.3.6/jar)

**Comment by ruippeixotog** [comment]
Hi everyone! Good news, I have just updated scala-scraper to support Scala 3 (3.1, more precisely)! I'll only be able to publish a new version to Maven on the week of Jun 6th, but I'll make sure to do it.

**Comment by ruippeixotog** [comment]
As promised, I have just released it. The artifact should be in Maven in a few hours. Thanks for your patience!
