### ISSUE TITLE
sbt dependency

### ISSUE THREAD

**Issue by calebbarr** [ruippeixotog/scala-scraper#18]
The sbt dependency doesn't work when copy-pasted.  The following fixes it:
`libraryDependencies += "net.ruippeixotog" % "scala-scraper_2.11" % "0.1.2"`

**Comment by ruippeixotog** [comment]
Hi @calebbarr! `"net.ruippeixotog" %% "scala-scraper" % "0.1.2"` is the same as `"net.ruippeixotog" % "scala-scraper_{SCALA_VERSION}" % "0.1.2"` (note the difference in the number of `%`). If you copy-paste the dependency to a Scala 2.11.x project, as the README indicates, then it works copy-pasted. You can read [this](http://www.scala-sbt.org/0.13/docs/Library-Dependencies.html#Getting+the+right+Scala+version+with) for more information.

Using the form you wrote in a Scala 2.10 project is not advised as the dependency was not compiled for that version and you may get ugly runtime errors. Pull request #17 aims to add support for Scala 2.10.x.

**Comment by calebbarr** [comment]
Hey @ruippeixotog thanks for the info.  Apparently, on my machine, `scala` runs 2.11.x, whereas `sbt console` by default runs 2.10.
