### ISSUE TITLE
Scalaz upgrade

### ISSUE THREAD

**Issue by fernando-torterolo** [ruippeixotog/scala-scraper#189]
Hi, After doing some upgrade of libraries, scala-scraper is failing with this error.

dependency version
- scalaScraper = "2.2.0"
- scalaz            = "7.3.3"

```
java.lang.NoSuchMethodError: scalaz.syntax.ToInvariantFunctorOps.$init$(Lscalaz/syntax/ToInvariantFunctorOps;)V
        at net.ruippeixotog.scalascraper.dsl.DSL$.<clinit>(DSL.scala:6)
```

do you have plans to move scalaz from 7.2.31 to a newer version?
many thanks for supporting this library

**Comment by ruippeixotog** [comment]
Closed by #190.
