### ISSUE TITLE
browser.get() not working for some URLs

### ISSUE THREAD

**Issue by piercelamb** [ruippeixotog/scala-scraper#22]
Hi,

I'm trying to scrape some public linkedin urls (ill use mine as an example) using:

val browser = new Browser
browser.get("https://www.linkedin.com/in/piercelamb"). 

This code is returning: 

"org.jsoup.HttpStatusException: HTTP error fetching URL"

And in some cases, returning a "status=999" which doesn't make sense. I *can* parse that link using pure Jsoup code, i.e.

Jsoup.connect("https://www.linkedin.com/in/piercelamb").get() just fine.

I tried updating from the 0.1.1 version of your artifact to 0.1.2. Also dug into the code somewhat and saw that you seemed to separate out a trait for Browser and 2 classes, though this doesn't appear to be reflected in the artifact. The only difference from base Jsoup code appears to be your executePipeline(...) function which im trying to understand since it is likely causing the problem. Perhaps its the default cookies you pass in defaultRequestSettings?

**Comment by ruippeixotog** [comment]
Hi! Yes, the `master` branch may be significantly different from v0.1.2, as I'm releasing v1.0.0 this week and that section has gone a major refactoring.

This is very strange... I'm experiencing the same error in v1.0.0, but it seems to be non-deterministic. Sometimes I repeat the request and it works well. Other times I execute the request directly using jsoup and I get the same exception you mentioned. Using the new `HtmlUnitBrowser`, based on [HtmlUnit](http://htmlunit.sourceforge.net/), an alternative to jsoup, I got:

```
org.apache.http.conn.HttpHostConnectException: Connect to www.linkedin.com:443 [www.linkedin.com/185.63.147.10, www.linkedin.com/2a04:f540:1:0:0:0:b93f:930a] failed: No route to host
```

By doing `ping www.linkedin.com`, I'm getting some very high latencies and even downtime periods:

```
64 bytes from 185.63.147.10: icmp_seq=70 ttl=50 time=54.975 ms
64 bytes from 185.63.147.10: icmp_seq=71 ttl=50 time=54.439 ms
64 bytes from 185.63.147.10: icmp_seq=72 ttl=50 time=73.677 ms
64 bytes from 185.63.147.10: icmp_seq=73 ttl=50 time=687.475 ms
64 bytes from 185.63.147.10: icmp_seq=74 ttl=50 time=917.092 ms
64 bytes from 185.63.147.10: icmp_seq=75 ttl=50 time=240.519 ms
64 bytes from 185.63.147.10: icmp_seq=76 ttl=50 time=56.649 ms
64 bytes from 185.63.147.10: icmp_seq=77 ttl=50 time=53.005 ms
64 bytes from 185.63.147.10: icmp_seq=78 ttl=50 time=52.787 ms
64 bytes from 185.63.147.10: icmp_seq=79 ttl=50 time=101.565 ms
Request timeout for icmp_seq 80
Request timeout for icmp_seq 81
Request timeout for icmp_seq 82
64 bytes from 185.63.147.10: icmp_seq=80 ttl=50 time=3209.547 ms
64 bytes from 185.63.147.10: icmp_seq=81 ttl=50 time=3328.162 ms
Request timeout for icmp_seq 85
Request timeout for icmp_seq 86
Request timeout for icmp_seq 87
64 bytes from 185.63.147.10: icmp_seq=82 ttl=50 time=6410.486 ms
64 bytes from 185.63.147.10: icmp_seq=83 ttl=50 time=6534.423 ms
64 bytes from 185.63.147.10: icmp_seq=84 ttl=50 time=6383.424 ms
64 bytes from 185.63.147.10: icmp_seq=85 ttl=50 time=6383.393 ms
64 bytes from 185.63.147.10: icmp_seq=86 ttl=50 time=6143.081 ms
64 bytes from 185.63.147.10: icmp_seq=87 ttl=50 time=5794.032 ms
```

Maybe this is a temporary problem with LinkedIn?

**Comment by piercelamb** [comment]
Interesting, yeah I'll try again tomorrow morning and see if anything has changed

**Comment by ruippeixotog** [comment]
Hi again @piercelamb! I have just tried yesterday's experience and it looks pings are now stable and I don't see any problems using `Browser#get`. Can you try it on your end?

**Comment by piercelamb** [comment]
Tried at it works fine. Definitely must have been on linkedin's end. Appreciate the quick replies.
