### ISSUE TITLE
A build for Scala 2.10 in maven central

### ISSUE THREAD

**Issue by dnrusakov** [ruippeixotog/scala-scraper#25]
Is it possible to upload a build for Scala 2.10 in maven central repository?

**Comment by ruippeixotog** [comment]
Hi @dnrusakov! Sorry for the (very) late reply, I totally forgot this issue...

There was some time ago [a pull request](https://github.com/ruippeixotog/scala-scraper/pull/17) for adding a Scala 2.10 build, but it had some problems and it had to be reverted. I'm willing to cross build for 2.10 if it compiles _without major modifications_ to the existing source code. Feel free to submit a pull request if you can get it to work :)

Even if a build gets to be published for the current version, please be aware that I won't guarantee that future versions will also support 2.10. As a rule of thumb, I'll drop support as soon as it keeps me from using a feature available only on newer Scala versions (either in the standard library itself or in a library that is only released for Scala 2.11+).

**Comment by dnrusakov** [comment]
Hi! Actually i no need a Scala 2.10 support anymore. But anyway, thanks!

**Comment by ruippeixotog** [comment]
Good! :) Sorry again for the delay.
