### ISSUE TITLE
Extracting text from a series of sibling elements

### ISSUE THREAD

**Issue by samikrc** [ruippeixotog/scala-scraper#27]
Hi,

This is not an issue report per se, but more like a support request. I am wondering if/how I can scrape the text/html data in the following case.

Let's assume that the HTML looks like this:

```html
<div id="mw-content-text" class="mw-content-ltr" lang="en" dir="ltr">
	<table class="infobox vevent" style="width:22em;font-size:90%;">...</table>
	<p>...</p>
	<p>...</p>
	<p>...</p>
	<h2>
		<span id="Plot" class="mw-headline">Plot</span>
		<span class="mw-editsection">
	</h2>
	<p>...</p>
	<p>...</p>
	<h2>
		<span id="Cast" class="mw-headline">Cast</span>
		<span class="mw-editsection">
	</h2>
	...
</div>
```
If you are wondering, this is how the movie pages in Wikipedia look like. I am trying to extract the plots of a bunch of movies. So essentially, what I have to do is, get the element corresponding to the "Plot" header (h2), and keep grabbing the texts from the [p] tags following that element, until I hit the next header (h2) tag.

Now, one way I can think of is to get all the elements in the top-level div, and then do this. It would work, but I am wondering if there is a smarter way to extract out these stuff? I can easily get to the "Plot" header (h2) element, but I couldn't figure out how I can get to the next few sibling elements from it till the next header (h2) tag.

Thanks.

**Comment by ruippeixotog** [comment]
Unfortunately I can't think of any way to do that using only CSS queries. I believe you'll have to retrieve and traverse the children of `#mw-content-text`.

If you want a suggestion of how to do that in a concise/elegant way, I'd probably do something like this:

```scala
  def separator(elem: Element): Option[String] = elem >?> text(".mw-headline")

  val movies = (doc >> elements("#mw-content-text > *"))
    .dropWhile(!separator(_).contains("Plot"))
    .drop(1)
    .takeWhile(separator(_).isEmpty)
```

`movies` will be a list of `p` elements from which you can further extract information.

**Comment by samikrc** [comment]
Thanks - was planning something similar. BTW, is there a complete api documentation, or the only way would be to go through the code?

**Comment by samikrc** [comment]
Worked nicely - this can be closed. Thanks again.

**Comment by ruippeixotog** [comment]
Right now the only documentation available is the README and the source code itself (with Scaladoc in most of the core classes). I'm aware it's not much, it could certainly be improved... I hope you can find your way through the API :)
