### ISSUE TITLE
Table data extractor

### ISSUE THREAD

**Issue by samikrc** [ruippeixotog/scala-scraper#30]
Hi,
Do you have code for extracting data from tables like you have for extracting data from forms? Because of the use of rowspan and colspan attributes, it gets difficult to parse a table from the raw html. Is there an easy way to do this from the in-memory rendering of the browsers?
Regards.

**Comment by ruippeixotog** [comment]
Hi! Currently there is no specialized extractor for HTML tables. It would be a nice addition to have one, but does come with its challenges. For example, what data structure did you have in mind? As you mentioned in your example, the ability of cells to cover an arbitrary number of rows and columns can make the organization rather messy...

**Comment by samikrc** [comment]
I have something in mind - let me see if I can open a pull request in a few weeks. If I do end up coding something, where do you think it would show up in the codebase? In scalascraper/scraper/HtmlExtractor.scala?

**Comment by ruippeixotog** [comment]
Yeah, I would expect it to be a new extractor in `ContentExtractors`. Looking forward to your pull request then!

**Comment by kumarivin** [comment]
hi, any update with this ?

**Comment by samikrc** [comment]
I worked on this a bit, but was unable to directly extend the library to 
include this feature (mostly because of my level of Scala skills). What 
I have is a standalone piece of code which does this. I can publish that 
code, and you can either use it as is, or try integrating this code in 
the library. Let me know if there is any interest.

Thanks.

**Comment by kumarivin** [comment]
Hello samikrc ,
Thanks a lot for quick response and yes, I would be happy to check it, please do publish.

**Comment by ruippeixotog** [comment]
It would be awesome if you shared your approach here, even if there was no interest now (which it seems there is), it would be a good resource for anyone dealing with this issue :) If the algorithm and data structure you chose to parse the table is general enough, I can surely help you implementing it in scala-scraper.

**Comment by samikrc** [comment]
Guys,

Sorry for the delay. Attaching two files, one containing the source code and the other containing some test code. Note that the test code is not automated - just some prints for manually checking if things look OK.

@ruippeixotog Saw your other email about the exciting features in the next version, including the "Content Extractors". This is probably too late to get included in that, but that is probably where this stuff can be integrated. 

Ready to answer questions :-)

Thanks.
-Samik

[TableExtractor.scala.txt](https://github.com/ruippeixotog/scala-scraper/files/1013235/TableExtractor.scala.txt)
[TableExtractorTester.scala.txt](https://github.com/ruippeixotog/scala-scraper/files/1013236/TableExtractorTester.scala.txt)

**Comment by samikrc** [comment]
Also note that some of the methods are just stubs, but are easy to implement. Important methods are already implemented.

**Comment by samikrc** [comment]
Hi, any update on this? Did the code get used somewhere?

**Comment by ruippeixotog** [comment]
Hi @samikrc, I ended up not using it anywhere for now - mostly due to my lack of time lately. I took a look at your code before and it seemed like a good implementation, it just needs to be converted to a more idiomatic extractor, like the regex extractors. I'll try to work on it in the next two weeks :)

**Comment by ruippeixotog** [comment]
I have just added a new `table` content extractor to scala-scraper (e7d3fe6c0a3461c0d1be513046c945d2b4e4cf58). I ended up writing the extractor from scratch, as it seemed easier for me to integrate it with the style of the other extractors this way.

Closing this now. If you find any bug with the implementation feel free to open another issue!
