### ISSUE TITLE
ignore some js when load a page with Htmlunit

### ISSUE THREAD

**Issue by temon** [ruippeixotog/scala-scraper#37]
I have to load a page that has a lot of javascript file that I should ignore it and just render several of their js files. I can not find any function to doing that. 

Also when I update the version to 1.1.0 at SBT build script, I search the close all function does not exist at Htmlunit class.

**Comment by ruippeixotog** [comment]
Hi @temon! Modifying pages and disabling selectively some of the scripts is out of the scope of scraping and thus, this library. If you really need to modify the page before "executing" it, I would probably load the page with jsoup directly, remove the `<script>` elements containing the JS you do not want to run, and then load the modified page in a `HtmlUnitBrowser` (via jsoup's `Node#outerHtml` and `Browser#parseString`).

Regarding the `closeAll` function, it will be released in the next version (see [CHANGELOG](https://github.com/ruippeixotog/scala-scraper/blob/master/CHANGELOG.md)). I'm just waiting for Scala 2.12.1 to be released (which should be very soon) so I can cross release the upcoming 1.2.0 version for both Scala 2.11 and 2.12.
