### ISSUE TITLE
Use Either instead of VSuccess/VFailure

### ISSUE THREAD

**Issue by tepf** [ruippeixotog/scala-scraper#38]
Would it be possible to use Either? As far as I know it would cover all the functionality of VSuccess and VFailure while reusing existing knowledge. It becomes especially interesting when using version 2.12, as  Either becomes right biased. This allows you to use it in for comprehensions and handle errors more smoothly.

**Comment by tepf** [comment]
Sorry my bad. I am new to Scala and didn't infer from the `README` that `Validated` just just an alias.

> I added them for code readability purposes, as I felt dealing with Either instances could lead to some confusion on which of the sides meant success and failure.

For me it was the other way around, but I don't know if that's the case for everybody else. I like to reuse as many concepts and names as possible.

**Comment by ruippeixotog** [comment]
Yes, I understand your point of view, and I agree it's not clear that `Validated` is an alias of `Either`. That could surely be improved :)

I have mixed feelings about using `Either` directly, in the same way I sometimes prefer specialized case classes to tuples. On one hand, `Either` implements an abstract concept of coproduct that has known properties and operations we can leverage. On the other hand, the subclasses of `Either` are not named, which can lead to confusion: if I run a validator with a `String` failure error through a `String` value, I end up with an `Either[String, String]`, a type that doesn't encode by itself whether it is a success or a failure. I meant readability in the sense of having self-describing code.

That said, I agree that the validation system could be improved - both on the data structures used and on some aspects of the DSL.

**Comment by tepf** [comment]
Yeah it's not absolutely clear which approach is better. Nevertheless I prefer reusing existing concepts/functionality. Not only because of familiarity but also less maintenance. Anyway, it's up to you. I'm sure you gave this more thought than me.

**Comment by ruippeixotog** [comment]
@tepf I ended up deprecating the usage of `Validated` in the latest version 2.0.0-RC2 in favor of `Either`. I'll close this issue now; thanks for reporting it!
