### ISSUE TITLE
XPath Support

### ISSUE THREAD

**Issue by Daxten** [ruippeixotog/scala-scraper#39]
is xpath support planned / already usable? couldn't find it in the docs

best regards

**Comment by ruippeixotog** [comment]
Hi @Daxten. I currently don't have XPath planned, as CSS queries provide the same functionality with better support in HTML parsers and engines such as jsoup. Do you have any use case that requires XPath specifically?

**Comment by Daxten** [comment]
No, it's just my go-to selector when using chrome.. but I guess it wouldn't be a problem to use the html-selector function :)

**Comment by zhenleibb** [comment]
> Hi @Daxten. I currently don't have XPath planned, as CSS queries provide the same functionality with better support in HTML parsers and engines such as jsoup. Do you have any use case that requires XPath specifically?

@ruippeixotog I have often hear xPath is more powerful than CSS, this article show a example:
https://medium.com/dataflow-kit/css-selectors-vs-xpath-f368b431c9dc

**Comment by ruippeixotog** [comment]
Hi @zhenleibb, jsoup's selector syntax goes further than CSS3 - in particular, it has the `:contains()` selector mentioned in the article. You can check what's supported in https://jsoup.org/cookbook/extracting-data/selector-syntax.
