### ISSUE TITLE
scalaz 7.0.6

### ISSUE THREAD

**Issue by angeloh** [ruippeixotog/scala-scraper#4]
Play 2.3 only supports scalaz 7.0.6. Can you please release a version that uses only Scalaz 7.0.6?

I got error with this string

val org_description: Option[String] = doc >?> text(".description-ellipsis.normal p")

java.lang.NoClassDefFoundError: scalaz/std/MapSubMap

I found out this MapSubMap only exists at 7.1.1 version.

**Comment by ruippeixotog** [comment]
From what I understood from [here](https://github.com/playframework/playframework/issues/3307), the only dependency of scalaz 7.0.6 in Play comes from the Play testkit (`play-test`), which uses an old version of `specs2` (which depends on scalaz 7.0.6 itself).

Do you use `play-test` features, like `FakeRequest` and `FakeApplication`? If you don't, maybe you can try excluding the dependency, as suggested in the issue I mentioned before? Like this:

```
libraryDependencies ~= (_.filterNot(d => d.organization == "com.typesafe.play" && d.name == "play-test")
```

I would rather not have to maintain two versions of the library with two different dependency versions, but if you use `play-test` or the solution above doesn't work for you for any reason, I can surely publish a version that specifically uses scalaz 7.0.x :)

**Comment by wiredin-io** [comment]
I got it sorted out. Thank you!

http://stackoverflow.com/a/30337491/772481

**Comment by ruippeixotog** [comment]
Great! I'm closing this issue then.
