### ISSUE TITLE
Wrong types in >?>

### ISSUE THREAD

**Issue by marcin-rzeznicki** [ruippeixotog/scala-scraper#42]
You have an error here https://github.com/ruippeixotog/scala-scraper/blob/master/src/main/scala/net/ruippeixotog/scalascraper/dsl/ScrapingOps.scala#L38 - `[B, C, D]` in signature vs `[B,C,C]` in params.

**Comment by ruippeixotog** [comment]
Indeed, thanks for the report! I have just fixed it in 238dec80852903b1071b92a0f5443be7b9c96401.

**Comment by marcin-rzeznicki** [comment]
Wow, that was quick :-) Thanks a lot 👍
