### ISSUE TITLE
Handling of missing tags

### ISSUE THREAD

**Issue by geoHeil** [ruippeixotog/scala-scraper#44]
How can I properly handle missing tags? I am running in quite some problems outlined http://stackoverflow.com/questions/43187383/spark-dataframe-handle-option-some-none and with a minimal sample of https://gist.github.com/geoHeil/bfb01427b88cf58ea755f912ce539712 sometimes I receive characters sometimes Strings.

**Comment by ruippeixotog** [comment]
Hi @geoHeil, I have just replied to your question at http://stackoverflow.com/a/43217110/603293. Please let me know if that helps you!
