### ISSUE TITLE
Chaining

### ISSUE THREAD

**Issue by wiradikusuma** [ruippeixotog/scala-scraper#48]
I want to get the `src` of a `<img class="large">` nested deep inside a div that **does not** have class `ignored`. This div is inside `<div id="foo">`.

In jQuery, this is how I do it:

    $('#foo > div').not('.ignored').find('img.large').attr('src')

How do I do it with scala-scraper?

**Comment by ruippeixotog** [comment]
Hi @wiradikusuma! You can do that with pure CSS using the [:not](https://developer.mozilla.org/en/docs/Web/CSS/:not) pseudo-class. In scala-scraper you would write something like:

```scala
doc >> attr("src")("#foo > div:not(.ignored) img.large")
// same as: doc >> "#foo > div:not(.ignored) img.large" >> attr("src")
```

**Comment by wiradikusuma** [comment]
@ruippeixotog it works, thanks!

For the benefit of others who do need chaining, is it supported (and how)? Otherwise, I'll just close this.

**Comment by ruippeixotog** [comment]
Yes, if you have to do some processing not supported by pure CSS, you have two approaches. You can either modify an existing extractor to do the extra filtering:

```scala
doc >> elementList("#foo > div").map(_.filter(_.attrs.get("class") != Some("ignored"))) >> "img.large" >> attr("src")
// equivalent to:
// val fooDivsExtractor = elementList("#foo > div").map(_.filter(_.attrs.get("class") != Some("ignored")))
// doc >> fooDivsExtractor >> "img.large" >> attr("src")
```

Or you can also do the extraction steps one at a time, filtering the results between them:

```scala
(doc >> elementList("#foo > div")).filter(_.attrs.get("class") != Some("ignored")) >> "img.large" >> attr("src")
// equivalent to:
// val fooDivs = doc >> elementList("#foo > div")
// val filteredFooDivs = fooDivs.filter(_.attrs.get("class") != Some("ignored"))
// filteredFooDivs >> "img.large" >> attr("src")
```

Does this answer your question?

**Comment by wiradikusuma** [comment]
Yes, thanks!
