### ISSUE TITLE
Build for scala 2.13.x 

### ISSUE THREAD

**Issue by frankivo** [ruippeixotog/scala-scraper#66]
2.13.0 has been released. Lot's of dependencies are not ready for a build however.

**Comment by ruippeixotog** [comment]
Somehow this slipped under my radar 😞I'm glad someone opened a pull request!

**Comment by ruippeixotog** [comment]
Sorry for the huge delay! I just published scala-scraper v2.2.0 with support for Scala 2.13, it should be available in Maven in 30 mins or so.
